# Generated by Django 5.2.4 on 2025-07-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='number_of_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
