# Generated by Django 5.2.4 on 2025-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_property_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(default='approved', max_length=20),
        ),
    ]
