# Generated by Django 5.2.4 on 2025-07-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_main_images/'),
        ),
    ]
