# Generated by Django 5.2.4 on 2025-07-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_property_agent_property_auctioneer_property_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='erf_size_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_garages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_kitchens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_parking_slots',
            field=models.CharField(blank=True, default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_erf_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
