# Generated by Django 5.2.4 on 2025-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proedge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('bank', 'Bank'), ('auctioneer', 'Auctioneer')], max_length=20),
        ),
    ]
